### ISSUE TITLE
Compatibility with Jellyfin

### ISSUE THREAD

**Issue by ryanwwest** [jacob-willden/script.movie.content.filter#1]
This work is great and something desperately needed since movie filter files could be easily distributed and used once created. But it seems to me that Kodi is a bit more dated, and things like Plex and Jellyfin have begun to supersede it for hosting content locally. With that said, I was wondering how compatible this might be with [Jellyfin](https://jellyfin.org/), or what sort of work might be needed to get it working there?

**Comment by jacob-willden** [comment]
So sorry for such a horribly late reply from me (almost 2 years!). I've been working on a [Jellyfin plugin](https://github.com/jacob-willden/jellyfin-plugin-moviecontentfilter) to achieve the same functionality. However, I hit a wall last year because the Jellyfin API does not allow for controlling the mute and seeking events programmatically, though I've been pushing to add that functionality into Jellyfin, but [my pull request](https://github.com/jellyfin/jellyfin/pull/9924) and its comments have gone largely ignored. I've been continuing to check up on the documentation since then, but still no changes have been made to Jellyfin to make this possible.

One other alternative could be making a fork of the repository, but I don't have the resources myself to distribute binaries through app stores (especially Apple's, which requires a yearly developer fee that I can't afford).

Sorry again for leaving you hanging for so long, it appears I had an issue with notification settings so I wasn't seeing issues in my repositories, but that's been fixed now.

**Comment by jacob-willden** [comment]
Actually, I have some good news! It appears that at least some of the developers of Jellyfin are open to the idea of adding edit decision list support (which my plugin would depend on): https://github.com/jellyfin/jellyfin-meta/discussions/30#discussioncomment-9629257

I'm going to follow the development of these features and see if there's anything I can do to contribute.

**Comment by ryanwwest** [comment]
Thanks for letting me know! I'm still very interested in this. Now following your other plugin and hoping jellyfin adds the support you need soon!

**Comment by ryanwwest** [comment]
@jacob-willden Jellyfin 10.10 just released and I see some features added that sound like what you were hoping for: https://github.com/jellyfin/jellyfin/releases/tag/v10.10.0.

**Comment by jacob-willden** [comment]
Sorry again for the late reply! Yes, the addition of `MediaSegments` brings us 1 step closer to EDL functionality. Sadly, we're still not there yet (based on my testing with Jellyfin), but I started [some discussion about it with the Jellyfin developers](https://github.com/jellyfin/jellyfin-meta/discussions/30#discussioncomment-11754086) a few days ago (I decided to wait until after the holidays to bring it up to them). Hopefully, it will go somewhere.

**Comment by jacob-willden** [comment]
Also, here's [some relevant discussion on the VideoSkip repository](https://github.com/fruiz500/VideoSkip/issues/7), and [some on the Movie Content Filter Website repository](https://github.com/delight-im/MovieContentFilter/issues/23).

**Comment by mcgeheecollier-ops** [comment]
Any update in the last year?  I am in the process of setting up my jellyfin server and have been scouring for some kind of content filtering, so definitely exciting to see that this is in progress.
